console.log("insert and removal concept")
let a=document.querySelector(".jas")
console.log(a)
// console.log(a.innerHtml="heloo.....")
// console.log(a.innerHTML)
// console.log(a.innerText)
// console.log(a.outerHTML)
let b=document.querySelector(".riya")
console.log(b.innerHTML)
console.log(b.innerText)
console.log(b.outerHTML)
console.log(b.tagName)
console.log(b.nodeName)
console.log(b.classList)
console.log(b.textContent)
// console.log(b.hidden)
console.log(b.insertAdjacentHTML("afterend","heloo <b> how r u</b>"))
// console.log(b.hidden=true)
// console.log(b.remove(hidden))

//attribute methods

console.log(a.innerHtml="hellooooo")
console.log(a.hasAttribute("style"))
console.log(a.setAttribute("style","display:flex"))
console.log(a.hasAttribute("style"))
console.log(a.Attributes)
// console.log(a.remove("style"))
// document.designMode="on"
console.log(b.dataset)

// insertion methodes
// let div=document.CreateElement('div')
// console.log(div.className="alert")
// div.setAttribute("class","created")
// div.innerHTML="r u riya <b>u r great</b>"
// console.log(document.querySelector(".riya").append(div))
console.log(b.classList)
console.log(b.classList.add("rinku"))
console.log(b.classList.add("rijas"))
console.log(b.className)
console.log(b.classList.remove("rinku"))
console.log(b.classList.toggle("rijas"))
console.log(b.className)
