let a=10;
let b=20;
//let c=a+b;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
console.log(a%b);
console.log((a-8)**(b-19));
let age=9;
(age<10)?console.log("u r a kid"):console.log('u r adult');