console.log("strings concept");
let a="riya";
console.log(a[0]);
console.log(a[1]);
console.log(a[2]);
console.log(a[5]);
console.log(a.length);
let b="Riya jasmineRi";
let c="jaya suneetha";
console.log(b.toUpperCase());
console.log(b.toLowerCase());
console.log(b.replace("Ri","22" ));
console.log(b.slice(1,25));
console.log(b.slice(1));
console.log(b.slice(0));
console.log(b.concat( a, c," rinku"," chikku"));
console.log("good"+b+"v.g"+c);
console.log(`good ${b} and v.g ${c}`);
console.log(b);
console.log("riya\"jasmine");